/** CATEGORY **/
export const ERR_CATEGORY_NOT_FOUND = "ERR_CATEGORY_NOT_FOUND";
export const ERR_CATEGORY_EXISTED = "ERR_CATEGORY_EXISTED";
export const ERR_CREATE_CATEGORY_FAIL = "ERR_CREATE_CATEGORY_FAIL";
export const ERR_UPDATE_CATEGORY_FAIL = "ERR_UPDATE_CATEGORY_FAIL";
export const ERR_DELETE_CATEGORY_FAIL = "ERR_DELETE_CATEGORY_FAIL";
export const ERR_HAVE_SUB_CATEGORIES = "ERR_HAVE_SUB_CATEGORIES";
export const ERR_PARENT_CATEGORY_NOT_EXISTS = "ERR_PARENT_CATEGORY_NOT_EXISTS";
export const ERR_CATEGORY_IDS_NOT_CORRECT = "ERR_CATEGORY_IDS_NOT_CORRECT";
export const ERR_RETRIEVE_CATEGORY_FAIL = "ERR_RETRIEVE_CATEGORY_FAIL";
export const ERR_CATEGORY_NAME_EXISTED = "ERR_CATEGORY_NAME_EXISTED";
export const ERR_CATEGORY_CODE_EXISTED = "ERR_CATEGORY_CODE_EXISTED";

/** ASSET **/
export const ERR_ASSET_STATE_NOT_CORRECT = "ERR_ASSET_STATE_NOT_CORRECT";
export const ERR_CREATE_ASSET_FAIL = "ERR_CREATE_ASSET_FAIL";
