// AUTH
export const ERR_ROLE_DONT_HAVE_PERMISSION = "Forbidden";
export const ERR_USER_UNAUTHORIZED = "Unauthorized";
export const ERR_ACCESS_IS_DENIED = "Access is denied";
export const ERR_BAD_CREDENTIALS = "Bad credentials";

/** CATEGORY **/
export const ERR_CATEGORY_NOT_FOUND = "ERR_CATEGORY_NOT_FOUND";
export const ERR_CATEGORY_EXISTED = "ERR_CATEGORY_EXISTED";
export const ERR_CREATE_CATEGORY_FAIL = "ERR_CREATE_CATEGORY_FAIL";
export const ERR_UPDATE_CATEGORY_FAIL = "ERR_UPDATE_CATEGORY_FAIL";
export const ERR_DELETE_CATEGORY_FAIL = "ERR_DELETE_CATEGORY_FAIL";
export const ERR_HAVE_SUB_CATEGORIES = "ERR_HAVE_SUB_CATEGORIES";
export const ERR_PARENT_CATEGORY_NOT_EXISTS = "ERR_PARENT_CATEGORY_NOT_EXISTS";
export const ERR_CATEGORY_IDS_NOT_CORRECT = "ERR_CATEGORY_IDS_NOT_CORRECT";
export const ERR_RETRIEVE_CATEGORY_FAIL = "ERR_RETRIEVE_CATEGORY_FAIL";
export const ERR_CATEGORY_NAME_EXISTED = "ERR_CATEGORY_NAME_EXISTED";
export const ERR_CATEGORY_CODE_EXISTED = "ERR_CATEGORY_CODE_EXISTED";

/** ASSET **/
export const ERR_ASSET_STATE_NOT_CORRECT = "ERR_ASSET_STATE_NOT_CORRECT";
export const ERR_CREATE_ASSET_FAIL = "ERR_CREATE_ASSET_FAIL";
export const ASSET_IS_NOT_AVAILABLE = "ASSET_IS_NOT_AVAILABLE";

// CHANGE PASS
export const ERR_USER_NOT_FOUND = "USER_NOT_FOUND";
export const ERR_PASSWORD_NOT_CORRECT = "PASSWORD_NOT_CORRECT";
export const ERR_PASSWORD_IS_EMPTY = "PASSWORD_IS_EMPTY";
export const ERR_SAME_PASSWORD = "SAME_PASSWORD";
export const ERR_CHANGE_PASSWORD = "ERR_CHANGE_PASSWORD";
